// src/constants/regions.ts

// 都道府県と市（東京都は特別区）を管理する型
export interface Prefecture {
  readonly name: string;
  readonly hiragana: readonly string[];
  readonly cities: readonly City[];
}

// 市（東京都は特別区）を管理する型
export interface City {
  readonly name: string;
  readonly hiragana:string;
}

// 地域と都道府県のデータを定義するための型
export interface Region {
  readonly name: string;
  readonly hiragana: string[];
  readonly prefectures: readonly Prefecture[];
}

// イベント一覧の地域フィルターで利用する地域・都道府県・市（東京都は特別区）のデータ
export const REGIONS: readonly Region[] = [
  // 北海道
  {
    name: "北海道",
    hiragana: ["ほっかいどう"],
    prefectures: [
      {
        name: "北海道",
        hiragana: ["ほっかいどう"],
        cities: [
          {name:"札幌市", hiragana:"さっぽろし"},
          {name:"函館市", hiragana:"はこだてし"},
          {name:"小樽市", hiragana:"おたるし"},
          {name:"旭川市", hiragana:"あさひかわし"},
          {name:"室蘭市", hiragana:"むろらんし"},
          {name:"釧路市", hiragana:"くしろし"},
          {name:"帯広市", hiragana:"おびひろし"},
          {name:"北見市", hiragana:"きたみし"},
          {name:"夕張市", hiragana:"ゆうばりし"},
          {name:"岩見沢市", hiragana:"いわみざわし"},
          {name:"網走市", hiragana:"あばしりし"},
          {name:"留萌市", hiragana:"るもいし"},
          {name:"苫小牧市", hiragana:"とまこまいし"},
          {name:"稚内市", hiragana:"わっかないし"},
          {name:"美唄市", hiragana:"びばいし"},
          {name:"芦別市", hiragana:"あしべつし"},
          {name:"江別市", hiragana:"えべつし"},
          {name:"赤平市", hiragana:"あかびらし"},
          {name:"紋別市", hiragana:"もんべつし"},
          {name:"士別市", hiragana:"しべつし"},
          {name:"名寄市", hiragana:"なよろし"},
          {name:"三笠市", hiragana:"みかさし"},
          {name:"根室市", hiragana:"ねむろし"},
          {name:"千歳市", hiragana:"ちとせし"},
          {name:"滝川市", hiragana:"たきかわし"},
          {name:"砂川市", hiragana:"すながわし"},
          {name:"歌志内市", hiragana:"うたしないし"},
          {name:"深川市", hiragana:"ふかがわし"},
          {name:"富良野市", hiragana:"ふらのし"},
          {name:"登別市", hiragana:"のぼりべつし"},
          {name:"恵庭市", hiragana:"えにわし"},
          {name:"伊達市", hiragana:"だてし"},
          {name:"北広島市", hiragana:"きたひろしまし"},
          {name:"石狩市", hiragana:"いしかりし"},
          {name:"北斗市", hiragana:"ほくとし"},
          {name:"石狩郡", hiragana:"いしかりぐん"},
          {name:"松前郡", hiragana:"まつまえぐん"},
          {name:"上磯郡", hiragana:"かみいそぐん"},
          {name:"亀田郡", hiragana:"かめだぐん"},
          {name:"茅部郡", hiragana:"かやべぐん"},
          {name:"二海郡", hiragana:"ふたみぐん"},
          {name:"山越郡", hiragana:"やまこしぐん"},
          {name:"檜山郡", hiragana:"ひやまぐん"},
          {name:"爾志郡", hiragana:"にしぐん"},
          {name:"奥尻郡", hiragana:"おくしりぐん"},
          {name:"瀬棚郡", hiragana:"せたなぐん"},
          {name:"久遠郡", hiragana:"くどうぐん"},
          {name:"島牧郡", hiragana:"しままきぐん"},
          {name:"寿都郡", hiragana:"すっつぐん"},
          {name:"磯谷郡", hiragana:"いそやぐん"},
          {name:"虻田郡", hiragana:"あぶたぐん"},
          {name:"岩内郡", hiragana:"いわないぐん"},
          {name:"古宇郡", hiragana:"ふるうぐん"},
          {name:"積丹郡", hiragana:"しゃこたんぐん"},
          {name:"余市郡", hiragana:"よいちぐん"},
          {name:"空知郡", hiragana:"そらちぐん"},
          {name:"夕張郡", hiragana:"ゆうばりぐん"},
          {name:"樺戸郡", hiragana:"かばとぐん"},
          {name:"雨竜郡", hiragana:"うりゅうぐん"},
          {name:"上川郡", hiragana:"かみかわぐん"},
          {name:"勇払郡", hiragana:"ゆうぶつぐん"},
          {name:"中川郡", hiragana:"なかがわぐん"},
          {name:"増毛郡", hiragana:"ましけぐん"},
          {name:"留萌郡", hiragana:"るもいぐん"},
          {name:"苫前郡", hiragana:"とままえぐん"},
          {name:"天塩郡", hiragana:"てしおぐん"},
          {name:"宗谷郡", hiragana:"そうやぐん"},
          {name:"枝幸郡", hiragana:"えさしぐん"},
          {name:"礼文郡", hiragana:"れぶんぐん"},
          {name:"利尻郡", hiragana:"りしりぐん"},
          {name:"網走郡", hiragana:"あばしりぐん"},
          {name:"斜里郡", hiragana:"しゃりぐん"},
          {name:"常呂郡", hiragana:"ところぐん"},
          {name:"紋別郡", hiragana:"もんべつぐん"},
          {name:"有珠郡", hiragana:"うすぐん"},
          {name:"白老郡", hiragana:"しらおいぐん"},
          {name:"新冠郡", hiragana:"にいかっぷぐん"},
          {name:"沙流郡", hiragana:"さるぐん"},
          {name:"浦河郡", hiragana:"うらかわぐん"},
          {name:"様似郡", hiragana:"さまにぐん"},
          {name:"幌泉郡", hiragana:"ほろいずみぐん"},
          {name:"日高郡", hiragana:"ひだかぐん"},
          {name:"河東郡", hiragana:"かとうぐん"},
          {name:"河西郡", hiragana:"かさいぐん"},
          {name:"広尾郡", hiragana:"ひろおぐん"},
          {name:"足寄郡", hiragana:"あしよろぐん"},
          {name:"十勝郡", hiragana:"とかちぐん"},
          {name:"釧路郡", hiragana:"くしろぐん"},
          {name:"厚岸郡", hiragana:"あっけしぐん"},
          {name:"川上郡", hiragana:"かわかみぐん"},
          {name:"標津郡", hiragana:"しべつぐん"},
          {name:"目梨郡", hiragana:"めなしぐん"},
          {name:"阿寒郡", hiragana:"あかんぐん"},
          {name:"白糠郡", hiragana:"しらぬかぐん"},
          {name:"野付郡", hiragana:"のつけぐん"},

        ],
      },
    
    ],
  },

  // 東北地方
  {
    name: "東北",
    hiragana: ["とうほく"],
    prefectures: [
      {
        name: "青森県",
        hiragana: ["あおもりけん"],
        cities: [
          {name:"青森市", hiragana:"あおもりし"},
          {name:"弘前市", hiragana:"ひろさきし"},
          {name:"八戸市", hiragana:"はちのへし"},
          {name:"黒石市", hiragana:"くろいしし"},
          {name:"五所川原市", hiragana:"ごしょがわらし"},
          {name:"十和田市", hiragana:"とわだし"},
          {name:"三沢市", hiragana:"みさわし"},
          {name:"むつ市", hiragana:"むつし"},
          {name:"つがる市", hiragana:"つがるし"},
          {name:"平川市", hiragana:"ひらかわし"},
          {name:"東津軽郡", hiragana:"ひがしつがるぐん"},
          {name:"西津軽郡", hiragana:"にしつがるぐん"},
          {name:"中津軽郡", hiragana:"なかつがるぐん"},
          {name:"南津軽郡", hiragana:"みなみつがるぐん"},
          {name:"北津軽郡", hiragana:"きたつがるぐん"},
          {name:"上北郡", hiragana:"かみきたぐん"},
          {name:"下北郡", hiragana:"しもきたぐん"},
          {name:"三戸郡", hiragana:"さんのへぐん"},

        ],
      },

      {
        name: "岩手県",
        hiragana: ["いわてけん"],
        cities: [
          {name:"盛岡市", hiragana:"もりおかし"},
          {name:"宮古市", hiragana:"みやこし"},
          {name:"大船渡市", hiragana:"おおふなとし"},
          {name:"花巻市", hiragana:"はなまきし"},
          {name:"北上市", hiragana:"きたかみし"},
          {name:"久慈市", hiragana:"くじし"},
          {name:"遠野市", hiragana:"とおのし"},
          {name:"一関市", hiragana:"いちせきし"},
          {name:"陸前高田市", hiragana:"りくぜんたかたし"},
          {name:"釜石市", hiragana:"かまいしし"},
          {name:"二戸市", hiragana:"にのへし"},
          {name:"八幡平市", hiragana:"はちまんたいし"},
          {name:"奥州市", hiragana:"おくしゅうし"},
          {name:"滝沢市", hiragana:"たきざわし"},
          {name:"岩手郡", hiragana:"いわてぐん"},
          {name:"紫波郡", hiragana:"しわぐん"},
          {name:"和賀郡", hiragana:"わがぐん"},
          {name:"胆沢郡", hiragana:"いさわぐん"},
          {name:"西磐井郡", hiragana:"にしいわいぐん"},
          {name:"気仙郡", hiragana:"けせんぐん"},
          {name:"上閉伊郡", hiragana:"かみへいぐん"},
          {name:"下閉伊郡", hiragana:"しもへいぐん"},
          {name:"九戸郡", hiragana:"くのへぐん"},
          {name:"二戸郡", hiragana:"にのへぐん"},

        ],
      },

      {
        name: "宮城県",
        hiragana: ["みやぎけん"],
        cities: [
          {name:"仙台市", hiragana:"せんだいし"},
          {name:"石巻市", hiragana:"いしがきし"},
          {name:"塩竈市", hiragana:"しおがまし"},
          {name:"気仙沼市", hiragana:"けせんぬまし"},
          {name:"白石市", hiragana:"しろいしし"},
          {name:"名取市", hiragana:"なとりし"},
          {name:"角田市", hiragana:"かくだし"},
          {name:"多賀城市", hiragana:"たがじょうし"},
          {name:"岩沼市", hiragana:"いわぬまし"},
          {name:"登米市", hiragana:"とめし"},
          {name:"栗原市", hiragana:"くりはらし"},
          {name:"東松島市", hiragana:"ひがしまつしまし"},
          {name:"大崎市", hiragana:"おおさきし"},
          {name:"富谷市", hiragana:"とみやし"},
          {name:"刈田郡", hiragana:"かったぐん"},
          {name:"柴田郡", hiragana:"しばたぐん"},
          {name:"伊具郡", hiragana:"いぐぐん"},
          {name:"亘理郡", hiragana:"わたりぐん"},
          {name:"宮城郡", hiragana:"みやぎぐん"},
          {name:"黒川郡", hiragana:"くろかわぐん"},
          {name:"加美郡", hiragana:"かみぐん"},
          {name:"遠田郡", hiragana:"とおだぐん"},
          {name:"牡鹿郡", hiragana:"おしかぐん"},
          {name:"本吉郡", hiragana:"もとよしぐん"},

        ],
      },

      {
        name: "秋田県",
        hiragana: ["あきたけん"],
        cities: [
          {name:"秋田市", hiragana:"あきたし"},
          {name:"能代市", hiragana:"のしろし"},
          {name:"横手市", hiragana:"よこてし"},
          {name:"大館市", hiragana:"おおだてし"},
          {name:"男鹿市", hiragana:"おがし"},
          {name:"湯沢市", hiragana:"ゆざわし"},
          {name:"鹿角市", hiragana:"かづのし"},
          {name:"由利本荘市", hiragana:"ゆりほんじょうし"},
          {name:"潟上市", hiragana:"かたがみし"},
          {name:"大仙市", hiragana:"だいせんし"},
          {name:"北秋田市", hiragana:"きたあきたし"},
          {name:"にかほ市", hiragana:"にかほし"},
          {name:"仙北市", hiragana:"せんぼくし"},
          {name:"鹿角郡", hiragana:"かづのぐん"},
          {name:"北秋田郡", hiragana:"きたあきたぐん"},
          {name:"山本郡", hiragana:"やまもとぐん"},
          {name:"南秋田郡", hiragana:"みなみあきたぐん"},
          {name:"仙北郡", hiragana:"せんぼくぐん"},
          {name:"雄勝郡", hiragana:"おがちぐん"},

        ],
      },

      {
        name: "山形県",
        hiragana: ["やまがたけん"],
        cities: [
          {name:"山形市", hiragana:"やまがたし"},
          {name:"米沢市", hiragana:"よねざわし"},
          {name:"鶴岡市", hiragana:"つるおかし"},
          {name:"酒田市", hiragana:"さかたし"},
          {name:"新庄市", hiragana:"しんじょうし"},
          {name:"寒河江市", hiragana:"さがえし"},
          {name:"上山市", hiragana:"かみのやまし"},
          {name:"村山市", hiragana:"むらやまし"},
          {name:"長井市", hiragana:"ながいし"},
          {name:"天童市", hiragana:"てんどうし"},
          {name:"東根市", hiragana:"ひがしねし"},
          {name:"尾花沢市", hiragana:"おばなざわし"},
          {name:"南陽市", hiragana:"なんようし"},
          {name:"東村山郡", hiragana:"ひがしむらやまぐん"},
          {name:"西村山郡", hiragana:"にしむらやまぐん"},
          {name:"北村山郡", hiragana:"きたむらやまぐん"},
          {name:"最上郡", hiragana:"もがみぐん"},
          {name:"東置賜郡", hiragana:"ひがしおきたまぐん"},
          {name:"西置賜郡", hiragana:"にしおきたまぐん"},
          {name:"東田川郡", hiragana:"ひがしたがわぐん"},
          {name:"飽海郡", hiragana:"あくみぐん"},

        ],
      },

      {
        name: "福島県",
        hiragana: ["ふくしまけん"],
        cities: [
          {name:"福島市", hiragana:"ふくしまし"},
          {name:"会津若松市", hiragana:"あいづわかまつし"},
          {name:"郡山市", hiragana:"こおりやまし"},
          {name:"いわき市", hiragana:"いわきし"},
          {name:"白河市", hiragana:"しらかわし"},
          {name:"須賀川市", hiragana:"すかがわし"},
          {name:"喜多方市", hiragana:"きたかたし"},
          {name:"相馬市", hiragana:"そうまし"},
          {name:"二本松市", hiragana:"にほんまつし"},
          {name:"田村市", hiragana:"たむらし"},
          {name:"南相馬市", hiragana:"みなみそうまし"},
          {name:"伊達市", hiragana:"だてし"},
          {name:"本宮市", hiragana:"もとみやし"},
          {name:"伊達郡", hiragana:"だてぐん"},
          {name:"安達郡", hiragana:"あだちぐん"},
          {name:"岩瀬郡", hiragana:"いわせぐん"},
          {name:"南会津郡", hiragana:"みなみあいづぐん"},
          {name:"耶麻郡", hiragana:"やまぐん"},
          {name:"河沼郡", hiragana:"かわぬまぐん"},
          {name:"大沼郡", hiragana:"おおぬまぐん"},
          {name:"西白河郡", hiragana:"にししらかわぐん"},
          {name:"東白川郡", hiragana:"ひがししらかわぐん"},
          {name:"石川郡", hiragana:"いしかわぐん"},
          {name:"田村郡", hiragana:"たむらぐん"},
          {name:"双葉郡", hiragana:"ふたばぐん"},
          {name:"相馬郡", hiragana:"そうまぐん"},

        ],
      },
    ],
  },

  // 関東地方
  {
    name: "関東",
    hiragana: ["かんとう"],
    prefectures: [
      {
        name: "茨城県",
        hiragana: ["いばらきけん"],
        cities: [
          {name:"水戸市", hiragana:"みずとし"},
          {name:"日立市", hiragana:"ひたちし"},
          {name:"土浦市", hiragana:"つちうらし"},
          {name:"古河市", hiragana:"こがし"},
          {name:"石岡市", hiragana:"いしおかし"},
          {name:"結城市", hiragana:"ゆうきし"},
          {name:"龍ヶ崎市", hiragana:"りゅうがさきし"},
          {name:"下妻市", hiragana:"しもつまし"},
          {name:"常総市", hiragana:"じょうそうし"},
          {name:"常陸太田市", hiragana:"ひたちおおたし"},
          {name:"高萩市", hiragana:"たかはぎし"},
          {name:"北茨城市", hiragana:"きたいばらきし"},
          {name:"笠間市", hiragana:"かさまし"},
          {name:"取手市", hiragana:"とりでし"},
          {name:"牛久市", hiragana:"うしくし"},
          {name:"つくば市", hiragana:"つくばし"},
          {name:"ひたちなか市", hiragana:"ひたちなかし"},
          {name:"鹿嶋市", hiragana:"かしまし"},
          {name:"潮来市", hiragana:"いたこし"},
          {name:"守谷市", hiragana:"もりやし"},
          {name:"常陸大宮市", hiragana:"ひたちおおみやし"},
          {name:"那珂市", hiragana:"なかし"},
          {name:"筑西市", hiragana:"ちくせいし"},
          {name:"坂東市", hiragana:"ばんどうし"},
          {name:"稲敷市", hiragana:"いなしきし"},
          {name:"かすみがうら市", hiragana:"かすみがうらし"},
          {name:"桜川市", hiragana:"さくらがわし"},
          {name:"神栖市", hiragana:"かみすし"},
          {name:"行方市", hiragana:"なめがたし"},
          {name:"鉾田市", hiragana:"ほこたし"},
          {name:"つくばみらい市", hiragana:"つくばみらいし"},
          {name:"小美玉市", hiragana:"おみたまし"},
          {name:"東茨城郡", hiragana:"ひがしいばらきぐん"},
          {name:"那珂郡", hiragana:"なかぐん"},
          {name:"久慈郡", hiragana:"くじぐん"},
          {name:"稲敷郡", hiragana:"いなしきぐん"},
          {name:"結城郡", hiragana:"ゆうきぐん"},
          {name:"猿島郡", hiragana:"さしまぐん"},
          {name:"北相馬郡", hiragana:"きたそうまぐん"},

        ],
      },

      {
        name: "栃木県",
        hiragana: ["とちぎけん"],
        cities: [
          {name:"宇都宮市", hiragana:"うつのみやし"},
          {name:"足利市", hiragana:"あしかがし"},
          {name:"栃木市", hiragana:"とちぎし"},
          {name:"佐野市", hiragana:"さのし"},
          {name:"鹿沼市", hiragana:"かぬまし"},
          {name:"日光市", hiragana:"にっこうし"},
          {name:"小山市", hiragana:"おやまし"},
          {name:"真岡市", hiragana:"もおかし"},
          {name:"大田原市", hiragana:"おおたわらし"},
          {name:"矢板市", hiragana:"やいたし"},
          {name:"那須塩原市", hiragana:"なすしおばらし"},
          {name:"さくら市", hiragana:"さくらし"},
          {name:"那須烏山市", hiragana:"なすからすやまし"},
          {name:"下野市", hiragana:"しもつけし"},
          {name:"河内郡", hiragana:"かわちぐん"},
          {name:"芳賀郡", hiragana:"はがぐん"},
          {name:"下都賀郡", hiragana:"しもつがぐん"},
          {name:"塩谷郡", hiragana:"しおやぐん"},
          {name:"那須郡", hiragana:"なすぐん"},

        ],
      },

      {
        name: "群馬県",
        hiragana: ["ぐんまけん"],
        cities: [
          {name:"前橋市", hiragana:"まえばしし"},
          {name:"高崎市", hiragana:"たかさきし"},
          {name:"桐生市", hiragana:"きりゅうし"},
          {name:"伊勢崎市", hiragana:"いせさきし"},
          {name:"太田市", hiragana:"おおたし"},
          {name:"沼田市", hiragana:"ぬまたし"},
          {name:"館林市", hiragana:"たてばやしし"},
          {name:"渋川市", hiragana:"しぶかわし"},
          {name:"藤岡市", hiragana:"ふじおかし"},
          {name:"富岡市", hiragana:"とみおかし"},
          {name:"安中市", hiragana:"あんなかし"},
          {name:"みどり市", hiragana:"みどりし"},
          {name:"北群馬郡", hiragana:"きたぐんまぐん"},
          {name:"多野郡", hiragana:"たのぐん"},
          {name:"甘楽郡", hiragana:"かんらぐん"},
          {name:"吾妻郡", hiragana:"あがつまぐん"},
          {name:"利根郡", hiragana:"とねぐん"},
          {name:"佐波郡", hiragana:"さわぐん"},
          {name:"邑楽郡", hiragana:"おうらぐん"},

        ],
      },

      {
        name: "埼玉県",
        hiragana: ["さいたまけん"],
        cities: [
          {name:"さいたま市", hiragana:"さいたまし"},
          {name:"川越市", hiragana:"かわごし"},
          {name:"熊谷市", hiragana:"くまがやし"},
          {name:"川口市", hiragana:"かわぐちし"},
          {name:"行田市", hiragana:"ぎょうだし"},
          {name:"秩父市", hiragana:"ちちぶし"},
          {name:"所沢市", hiragana:"ところざわし"},
          {name:"飯能市", hiragana:"はんのうし"},
          {name:"加須市", hiragana:"かぞし"},
          {name:"本庄市", hiragana:"ほんじょうし"},
          {name:"東松山市", hiragana:"ひがしまつやまし"},
          {name:"春日部市", hiragana:"かすかべし"},
          {name:"狭山市", hiragana:"さやまし"},
          {name:"羽生市", hiragana:"はにゅうし"},
          {name:"鴻巣市", hiragana:"こうのすし"},
          {name:"深谷市", hiragana:"ふかやし"},
          {name:"上尾市", hiragana:"あげおし"},
          {name:"草加市", hiragana:"そうかし"},
          {name:"越谷市", hiragana:"こしがやし"},
          {name:"蕨市", hiragana:"わらびし"},
          {name:"戸田市", hiragana:"とだし"},
          {name:"入間市", hiragana:"いるまし"},
          {name:"朝霞市", hiragana:"あさかし"},
          {name:"志木市", hiragana:"しきし"},
          {name:"和光市", hiragana:"わこうし"},
          {name:"新座市", hiragana:"にいざし"},
          {name:"桶川市", hiragana:"おけがわし"},
          {name:"久喜市", hiragana:"くきし"},
          {name:"北本市", hiragana:"きたもとし"},
          {name:"八潮市", hiragana:"やしおし"},
          {name:"富士見市", hiragana:"ふじみし"},
          {name:"三郷市", hiragana:"みさとし"},
          {name:"蓮田市", hiragana:"はすだし"},
          {name:"坂戸市", hiragana:"さかどし"},
          {name:"幸手市", hiragana:"さってし"},
          {name:"鶴ヶ島市", hiragana:"つるがしまし"},
          {name:"日高市", hiragana:"ひだかし"},
          {name:"吉川市", hiragana:"よしかわし"},
          {name:"ふじみ野市", hiragana:"ふじみのし"},
          {name:"白岡市", hiragana:"しらおかし"},
          {name:"北足立郡", hiragana:"きたあだちぐん"},
          {name:"入間郡", hiragana:"いるまぐん"},
          {name:"比企郡", hiragana:"ひきぐん"},
          {name:"秩父郡", hiragana:"ちちぶぐん"},
          {name:"児玉郡", hiragana:"こだまぐん"},
          {name:"大里郡", hiragana:"おおさとぐん"},
          {name:"南埼玉郡", hiragana:"みなみさいたまぐん"},
          {name:"北葛飾郡", hiragana:"きたかつしかぐん"},

        ],
      },

      {
        name: "千葉県",
        hiragana: ["ちばけん"],
        cities: [
          {name:"千葉市", hiragana:"ちばし"},
          {name:"銚子市", hiragana:"ちょうしし"},
          {name:"市川市", hiragana:"いちかわし"},
          {name:"船橋市", hiragana:"ふなばしし"},
          {name:"館山市", hiragana:"たてやまし"},
          {name:"木更津市", hiragana:"きさらづし"},
          {name:"松戸市", hiragana:"まつどし"},
          {name:"野田市", hiragana:"のだし"},
          {name:"茂原市", hiragana:"もばらし"},
          {name:"成田市", hiragana:"なりたし"},
          {name:"佐倉市", hiragana:"さくらし"},
          {name:"東金市", hiragana:"とうがねし"},
          {name:"旭市", hiragana:"あさひし"},
          {name:"習志野市", hiragana:"ならしのし"},
          {name:"柏市", hiragana:"かしわし"},
          {name:"勝浦市", hiragana:"かつうらし"},
          {name:"市原市", hiragana:"いちはらし"},
          {name:"流山市", hiragana:"ながれやまし"},
          {name:"八千代市", hiragana:"やちよし"},
          {name:"我孫子市", hiragana:"あびこし"},
          {name:"鴨川市", hiragana:"かもがわし"},
          {name:"鎌ケ谷市", hiragana:"かまがやし"},
          {name:"君津市", hiragana:"きみつし"},
          {name:"富津市", hiragana:"ふっつし"},
          {name:"浦安市", hiragana:"うらやすし"},
          {name:"四街道市", hiragana:"よつかいどうし"},
          {name:"袖ケ浦市", hiragana:"そでがうらし"},
          {name:"八街市", hiragana:"やちまたし"},
          {name:"印西市", hiragana:"いんざいし"},
          {name:"白井市", hiragana:"しろいし"},
          {name:"富里市", hiragana:"とみさとし"},
          {name:"南房総市", hiragana:"みなみぼうそうし"},
          {name:"匝瑳市", hiragana:"そうさし"},
          {name:"香取市", hiragana:"かとりし"},
          {name:"山武市", hiragana:"さんむし"},
          {name:"いすみ市", hiragana:"いすみし"},
          {name:"大網白里市", hiragana:"おおあみしらさとし"},
          {name:"印旛郡", hiragana:"いんばぐん"},
          {name:"香取郡", hiragana:"かとりぐん"},
          {name:"山武郡", hiragana:"さんぶぐん"},
          {name:"長生郡", hiragana:"ちょうせいぐん"},
          {name:"夷隅郡", hiragana:"いすみぐん"},
          {name:"安房郡", hiragana:"あわぐん"},

        ],
      },

      {
        name: "東京都",
        hiragana: ["とうきょうと"],
        cities: [
          {name:"特別区部23区", hiragana:"とくべつくぶにじゅうさんく"},
          {name:"八王子市", hiragana:"はちおうじし"},
          {name:"立川市", hiragana:"たちかわし"},
          {name:"武蔵野市", hiragana:"むさしのし"},
          {name:"三鷹市", hiragana:"みたかし"},
          {name:"青梅市", hiragana:"おうめし"},
          {name:"府中市", hiragana:"ふちゅうし"},
          {name:"昭島市", hiragana:"あきしまし"},
          {name:"調布市", hiragana:"ちょうふし"},
          {name:"町田市", hiragana:"まちだし"},
          {name:"小金井市", hiragana:"こがねいし"},
          {name:"小平市", hiragana:"こだいらし"},
          {name:"日野市", hiragana:"ひのし"},
          {name:"東村山市", hiragana:"ひがしむらやまし"},
          {name:"国分寺市", hiragana:"こくぶんじし"},
          {name:"国立市", hiragana:"くにたちし"},
          {name:"福生市", hiragana:"ふっさし"},
          {name:"狛江市", hiragana:"こまえし"},
          {name:"東大和市", hiragana:"ひがしやまとし"},
          {name:"清瀬市", hiragana:"きよせし"},
          {name:"東久留米市", hiragana:"ひがしくるめし"},
          {name:"武蔵村山市", hiragana:"むさしむらやまし"},
          {name:"多摩市", hiragana:"たまし"},
          {name:"稲城市", hiragana:"いなぎし"},
          {name:"羽村市", hiragana:"はむらし"},
          {name:"あきる野市", hiragana:"あきるのし"},
          {name:"西東京市", hiragana:"にしとうきょうし"},
          {name:"西多摩郡", hiragana:"にしたまぐん"},
          {name:"大島支庁", hiragana:"おおしましちょう"},
          {name:"三宅支庁", hiragana:"みやけしちょう"},
          {name:"八丈支庁", hiragana:"はちじょうしちょう"},
          {name:"小笠原支庁", hiragana:"おがさわらしちょう"},

        ],
      },

      {
        name: "神奈川県",
        hiragana: ["かながわけん"],
        cities: [
          {name:"横浜市", hiragana:"よこはまし"},
          {name:"川崎市", hiragana:"かわさきし"},
          {name:"相模原市", hiragana:"さがみはらし"},
          {name:"横須賀市", hiragana:"よこすかし"},
          {name:"平塚市", hiragana:"ひらつかし"},
          {name:"鎌倉市", hiragana:"かまくらし"},
          {name:"藤沢市", hiragana:"ふじさわし"},
          {name:"小田原市", hiragana:"おだはらし"},
          {name:"茅ヶ崎市", hiragana:"ちがさきし"},
          {name:"逗子市", hiragana:"ずしし"},
          {name:"三浦市", hiragana:"みうらし"},
          {name:"秦野市", hiragana:"はだのし"},
          {name:"厚木市", hiragana:"あつぎし"},
          {name:"大和市", hiragana:"やまとし"},
          {name:"伊勢原市", hiragana:"いせはらし"},
          {name:"海老名市", hiragana:"えびなし"},
          {name:"座間市", hiragana:"ざまし"},
          {name:"南足柄市", hiragana:"みなみあしがらし"},
          {name:"綾瀬市", hiragana:"あやせし"},
          {name:"三浦郡", hiragana:"みうらぐん"},
          {name:"高座郡", hiragana:"こうざぐん"},
          {name:"中郡", hiragana:"なかぐん"},
          {name:"足柄上郡", hiragana:"あしがらかみぐん"},
          {name:"足柄下郡", hiragana:"あしがらしもぐん"},
          {name:"愛甲郡", hiragana:"あいこうぐん"},

        ],
      },
    ],
  },

  // 中部地方
  {
    name: "中部",
    hiragana: ["ちゅうぶ"],
    prefectures: [
    
      {
         name: "新潟県", hiragana: ["にいがたけん"],
         cities: [
          {name:"新潟市", hiragana:"にいがたし"},
          {name:"長岡市", hiragana:"ながおかし"},
          {name:"三条市", hiragana:"さんじょうし"},
          {name:"柏崎市", hiragana:"かしわざきし"},
          {name:"新発田市", hiragana:"しばたし"},
          {name:"小千谷市", hiragana:"おぢやし"},
          {name:"加茂市", hiragana:"かもし"},
          {name:"十日町市", hiragana:"とおかまちし"},
          {name:"見附市", hiragana:"みつけし"},
          {name:"村上市", hiragana:"むらかみし"},
          {name:"燕市", hiragana:"つばめし"},
          {name:"糸魚川市", hiragana:"いといがわし"},
          {name:"妙高市", hiragana:"みょうこうし"},
          {name:"五泉市", hiragana:"ごせんし"},
          {name:"上越市", hiragana:"じょうえつし"},
          {name:"阿賀野市", hiragana:"あがのし"},
          {name:"佐渡市", hiragana:"さどし"},
          {name:"魚沼市", hiragana:"うおぬまし"},
          {name:"南魚沼市", hiragana:"みなみうおぬまし"},
          {name:"胎内市", hiragana:"たいないし"},
          {name:"北蒲原郡", hiragana:"きたかんばらぐん"},
          {name:"西蒲原郡", hiragana:"にしかんばらぐん"},
          {name:"南蒲原郡", hiragana:"みなみかんばらぐん"},
          {name:"東蒲原郡", hiragana:"ひがしかんばらぐん"},
          {name:"三島郡", hiragana:"さんとうぐん"},
          {name:"南魚沼郡", hiragana:"みなみうおぬまぐん"},
          {name:"中魚沼郡", hiragana:"なかうおぬまぐん"},
          {name:"刈羽郡", hiragana:"かりわぐん"},
          {name:"岩船郡", hiragana:"いわふねぐん"},

        ] 
      },

      { 
        name: "富山県", hiragana: ["とやまけん"], 
        cities: [
          {name:"富山市", hiragana:"とやまし"},
          {name:"高岡市", hiragana:"たかおかし"},
          {name:"魚津市", hiragana:"うおづし"},
          {name:"氷見市", hiragana:"ひみし"},
          {name:"滑川市", hiragana:"なめりかわし"},
          {name:"黒部市", hiragana:"くろべし"},
          {name:"砺波市", hiragana:"となみし"},
          {name:"小矢部市", hiragana:"おやべし"},
          {name:"南砺市", hiragana:"なんとし"},
          {name:"射水市", hiragana:"いみずし"},
          {name:"中新川郡", hiragana:"なかにいかわぐん"},
          {name:"下新川郡", hiragana:"しもにいかわぐん"},

        ],
       },

      { 
        name: "石川県", hiragana: ["いしかわけん"],
         cities: [
          {name:"金沢市", hiragana:"かなざわし"},
          {name:"七尾市", hiragana:"ななおし"},
          {name:"小松市", hiragana:"こまつし"},
          {name:"輪島市", hiragana:"わじまし"},
          {name:"珠洲市", hiragana:"すずし"},
          {name:"加賀市", hiragana:"かがし"},
          {name:"羽咋市", hiragana:"はくいし"},
          {name:"かほく市", hiragana:"かほくし"},
          {name:"白山市", hiragana:"はくさんし"},
          {name:"能美市", hiragana:"のみし"},
          {name:"野々市市", hiragana:"ののしし"},
          {name:"能美郡", hiragana:"のみぐん"},
          {name:"河北郡", hiragana:"かほくぐん"},
          {name:"羽咋郡", hiragana:"はくいぐん"},
          {name:"鹿島郡", hiragana:"かしまぐん"},
          {name:"鳳珠郡", hiragana:"ほうすぐん"},

        ], 
      },

      {
        name: "福井県", hiragana: ["ふくいけん"], 
        cities: [
          {name:"福井市", hiragana:"ふくいし"},
          {name:"敦賀市", hiragana:"つるがし"},
          {name:"小浜市", hiragana:"おばまし"},
          {name:"大野市", hiragana:"おおのし"},
          {name:"勝山市", hiragana:"かつやまし"},
          {name:"鯖江市", hiragana:"さばえし"},
          {name:"あわら市", hiragana:"あわらし"},
          {name:"越前市", hiragana:"えちぜんし"},
          {name:"坂井市", hiragana:"さかいし"},
          {name:"吉田郡", hiragana:"よしだぐん"},
          {name:"今立郡", hiragana:"いまだてぐん"},
          {name:"南条郡", hiragana:"なんじょうぐん"},
          {name:"丹生郡", hiragana:"にゅうぐん"},
          {name:"三方郡", hiragana:"みかたぐん"},
          {name:"大飯郡", hiragana:"おおいんぐん"},
          {name:"三方上中郡", hiragana:"みかたかみなかぐん"},

        ],
       },
      
      { 
        name: "山梨県", hiragana: ["やまなしけん"],
        cities: [
          {name:"甲府市", hiragana:"こうふし"},
          {name:"富士吉田市", hiragana:"ふじよしだし"},
          {name:"都留市", hiragana:"つるし"},
          {name:"山梨市", hiragana:"やまなしし"},
          {name:"大月市", hiragana:"おおつきし"},
          {name:"韮崎市", hiragana:"にらさきし"},
          {name:"南アルプス市", hiragana:"みなみあるぷすし"},
          {name:"北杜市", hiragana:"ほくとし"},
          {name:"甲斐市", hiragana:"かいし"},
          {name:"笛吹市", hiragana:"ふえふきし"},
          {name:"上野原市", hiragana:"うえのはらし"},
          {name:"甲州市", hiragana:"こうしゅうし"},
          {name:"中央市", hiragana:"ちゅうおうし"},
          {name:"西八代郡", hiragana:"にしやつしろぐん"},
          {name:"南巨摩郡", hiragana:"みなみこまぐん"},
          {name:"中巨摩郡", hiragana:"なかこまぐん"},
          {name:"南都留郡", hiragana:"みなみつるぐん"},
          {name:"北都留郡", hiragana:"きたつるぐん"},

        ],
       },
      
      { 
        name: "長野県", hiragana: ["ながのけん"],
        cities: [
          {name:"長野市", hiragana:"ながのし"},
          {name:"松本市", hiragana:"まつもとし"},
          {name:"上田市", hiragana:"うえだし"},
          {name:"岡谷市", hiragana:"おかやし"},
          {name:"飯田市", hiragana:"いいだし"},
          {name:"諏訪市", hiragana:"すわし"},
          {name:"須坂市", hiragana:"すざかし"},
          {name:"小諸市", hiragana:"こもろし"},
          {name:"伊那市", hiragana:"いなし"},
          {name:"駒ヶ根市", hiragana:"こまがねし"},
          {name:"中野市", hiragana:"なかのし"},
          {name:"大町市", hiragana:"おおまちし"},
          {name:"飯山市", hiragana:"いいやまし"},
          {name:"茅野市", hiragana:"ちのし"},
          {name:"塩尻市", hiragana:"しおじりし"},
          {name:"佐久市", hiragana:"さくし"},
          {name:"千曲市", hiragana:"ちくまし"},
          {name:"東御市", hiragana:"とうみし"},
          {name:"安曇野市", hiragana:"あずみのし"},
          {name:"南佐久郡", hiragana:"みなみさくぐん"},
          {name:"北佐久郡", hiragana:"きたさくぐん"},
          {name:"小県郡", hiragana:"ちいさがたぐん"},
          {name:"諏訪郡", hiragana:"すわぐん"},
          {name:"上伊那郡", hiragana:"かみいなぐん"},
          {name:"下伊那郡", hiragana:"しもいなぐん"},
          {name:"木曽郡", hiragana:"きそぐん"},
          {name:"東筑摩郡", hiragana:"ひがしちくまぐん"},
          {name:"北安曇郡", hiragana:"きたあずみぐん"},
          {name:"埴科郡", hiragana:"はにしなぐん"},
          {name:"上高井郡", hiragana:"かみたかいぐん"},
          {name:"下高井郡", hiragana:"しもたかいぐん"},
          {name:"上水内郡", hiragana:"かみみのちぐん"},
          {name:"下水内郡", hiragana:"しもみのちぐん"},

        ],
       },

      { 
        name: "岐阜県", hiragana: ["ぎふけん"],
        cities: [
          {name:"岐阜市", hiragana:"きふし"},
          {name:"大垣市", hiragana:"おがきし"},
          {name:"高山市", hiragana:"たかやまし"},
          {name:"多治見市", hiragana:"たじみし"},
          {name:"関市", hiragana:"せきし"},
          {name:"中津川市", hiragana:"なかつがわし"},
          {name:"美濃市", hiragana:"みのし"},
          {name:"瑞浪市", hiragana:"みずなみし"},
          {name:"羽島市", hiragana:"はしまし"},
          {name:"恵那市", hiragana:"えなし"},
          {name:"美濃加茂市", hiragana:"みのかもし"},
          {name:"土岐市", hiragana:"ときし"},
          {name:"各務原市", hiragana:"かかみがはらし"},
          {name:"可児市", hiragana:"かにし"},
          {name:"山県市", hiragana:"やまがたし"},
          {name:"瑞穂市", hiragana:"みずほし"},
          {name:"飛騨市", hiragana:"ひだし"},
          {name:"本巣市", hiragana:"もとすし"},
          {name:"郡上市", hiragana:"ぐじょうし"},
          {name:"下呂市", hiragana:"げろし"},
          {name:"海津市", hiragana:"かいづし"},
          {name:"羽島郡", hiragana:"はしまぐん"},
          {name:"養老郡", hiragana:"ようろうぐん"},
          {name:"不破郡", hiragana:"ふわぐん"},
          {name:"安八郡", hiragana:"あんぱちぐん"},
          {name:"揖斐郡", hiragana:"いびぐん"},
          {name:"本巣郡", hiragana:"もとすぐん"},
          {name:"加茂郡", hiragana:"かもぐん"},
          {name:"可児郡", hiragana:"かにぐん"},
          {name:"大野郡", hiragana:"おおのぐん"},

        ],
       },

      { 
        name: "静岡県", hiragana: ["しずおかけん"],
        cities: [
          {name:"静岡市", hiragana:"しずおかし"},
          {name:"浜松市", hiragana:"はままつし"},
          {name:"沼津市", hiragana:"ぬまづし"},
          {name:"熱海市", hiragana:"あたみし"},
          {name:"三島市", hiragana:"みしまし"},
          {name:"富士宮市", hiragana:"ふじのみやし"},
          {name:"伊東市", hiragana:"いとうし"},
          {name:"島田市", hiragana:"しまだし"},
          {name:"富士市", hiragana:"ふじし"},
          {name:"磐田市", hiragana:"いわたし"},
          {name:"焼津市", hiragana:"やいづし"},
          {name:"掛川市", hiragana:"かけがわし"},
          {name:"藤枝市", hiragana:"ふじえだし"},
          {name:"御殿場市", hiragana:"ごてんばし"},
          {name:"袋井市", hiragana:"ふくろいし"},
          {name:"下田市", hiragana:"しもだし"},
          {name:"裾野市", hiragana:"すそのし"},
          {name:"湖西市", hiragana:"こさいし"},
          {name:"伊豆市", hiragana:"いずし"},
          {name:"御前崎市", hiragana:"おまえざきし"},
          {name:"菊川市", hiragana:"きくがわし"},
          {name:"伊豆の国市", hiragana:"いずのくにし"},
          {name:"牧之原市", hiragana:"まきのはらし"},
          {name:"賀茂郡", hiragana:"かもぐん"},
          {name:"田方郡", hiragana:"たがたぐん"},
          {name:"駿東郡", hiragana:"すんとうぐん"},
          {name:"榛原郡", hiragana:"はいばらぐん"},
          {name:"周智郡", hiragana:"しゅうちぐん"},

        ],
       },
      
      {
        name: "愛知県",
        hiragana: ["あいちけん"],
        cities: [
          {name:"名古屋市", hiragana:"なごやし"},
          {name:"豊橋市", hiragana:"とよはしし"},
          {name:"岡崎市", hiragana:"おかざきし"},
          {name:"一宮市", hiragana:"いちのみやし"},
          {name:"瀬戸市", hiragana:"せとし"},
          {name:"半田市", hiragana:"はんだし"},
          {name:"春日井市", hiragana:"かすがいし"},
          {name:"豊川市", hiragana:"とよかわし"},
          {name:"津島市", hiragana:"つしまし"},
          {name:"碧南市", hiragana:"へきなんし"},
          {name:"刈谷市", hiragana:"かりやし"},
          {name:"豊田市", hiragana:"とよたし"},
          {name:"安城市", hiragana:"あんじょうし"},
          {name:"西尾市", hiragana:"にしおし"},
          {name:"蒲郡市", hiragana:"がまごおりし"},
          {name:"犬山市", hiragana:"いぬやまし"},
          {name:"常滑市", hiragana:"とこなめし"},
          {name:"江南市", hiragana:"こうなんし"},
          {name:"小牧市", hiragana:"こまきし"},
          {name:"稲沢市", hiragana:"いなざわし"},
          {name:"新城市", hiragana:"しんしろし"},
          {name:"東海市", hiragana:"とうかいし"},
          {name:"大府市", hiragana:"おおぶし"},
          {name:"知多市", hiragana:"ちたし"},
          {name:"知立市", hiragana:"ちりゅうし"},
          {name:"尾張旭市", hiragana:"おわりあさひし"},
          {name:"高浜市", hiragana:"たかはまし"},
          {name:"岩倉市", hiragana:"いわくらし"},
          {name:"豊明市", hiragana:"とよあけし"},
          {name:"日進市", hiragana:"にっしんし"},
          {name:"田原市", hiragana:"たはらし"},
          {name:"愛西市", hiragana:"あいさいし"},
          {name:"清須市", hiragana:"きよすし"},
          {name:"北名古屋市", hiragana:"きたなごやし"},
          {name:"弥富市", hiragana:"やとみし"},
          {name:"みよし市", hiragana:"みよしし"},
          {name:"あま市", hiragana:"あまし"},
          {name:"長久手市", hiragana:"ながくてし"},
          {name:"愛知郡", hiragana:"あいちぐん"},
          {name:"西春日井郡", hiragana:"にしかすがいぐん"},
          {name:"丹羽郡", hiragana:"にわぐん"},
          {name:"海部郡", hiragana:"あまぐん"},
          {name:"知多郡", hiragana:"ちたぐん"},
          {name:"額田郡", hiragana:"ぬかたぐん"},
          {name:"北設楽郡", hiragana:"きたしたらぐん"},

        ],
      },
    ],
  },

  // 近畿地方
  {
    name: "近畿",
    hiragana: ["きんき"],
    prefectures: [
      {
        name: "三重県",
        hiragana: ["みえけん"],
        cities: [
          {name:"津市", hiragana:"つし"},
          {name:"四日市市", hiragana:"よっかいちし"},
          {name:"伊勢市", hiragana:"いせし"},
          {name:"松阪市", hiragana:"まつさかし"},
          {name:"桑名市", hiragana:"くわなし"},
          {name:"鈴鹿市", hiragana:"すずかし"},
          {name:"名張市", hiragana:"なばりし"},
          {name:"尾鷲市", hiragana:"おわせし"},
          {name:"亀山市", hiragana:"かめやまし"},
          {name:"鳥羽市", hiragana:"とばし"},
          {name:"熊野市", hiragana:"くまのし"},
          {name:"いなべ市", hiragana:"いなべし"},
          {name:"志摩市", hiragana:"しまし"},
          {name:"伊賀市", hiragana:"いがし"},
          {name:"桑名郡", hiragana:"くわなぐん"},
          {name:"員弁郡", hiragana:"いなべぐん"},
          {name:"三重郡", hiragana:"みえぐん"},
          {name:"多気郡", hiragana:"たきぐん"},
          {name:"度会郡", hiragana:"わたらいぐん"},
          {name:"北牟婁郡", hiragana:"きたむろぐん"},
          {name:"南牟婁郡", hiragana:"みなみむろぐん"},

        ],
      },

      {
        name: "滋賀県",
        hiragana: ["しがけん"],
        cities: [
          {name:"大津市", hiragana:"おおつし"},
          {name:"彦根市", hiragana:"ひこねし"},
          {name:"長浜市", hiragana:"ながはまし"},
          {name:"近江八幡市", hiragana:"おうみはちまんし"},
          {name:"草津市", hiragana:"くさつし"},
          {name:"守山市", hiragana:"もりやまし"},
          {name:"栗東市", hiragana:"りっとうし"},
          {name:"甲賀市", hiragana:"こうかし"},
          {name:"野洲市", hiragana:"やすし"},
          {name:"湖南市", hiragana:"こなんし"},
          {name:"高島市", hiragana:"たかしまし"},
          {name:"東近江市", hiragana:"ひがしおうみし"},
          {name:"米原市", hiragana:"まいばらし"},
          {name:"蒲生郡", hiragana:"がもうぐん"},
          {name:"愛知郡", hiragana:"えちぐん"},
          {name:"犬上郡", hiragana:"いぬかみぐん"},

        ],
      },

      {
        name: "京都府",
        hiragana: ["きょうとふ"],
        cities: [
          {name:"京都市", hiragana:"きょうとし"},
          {name:"福知山市", hiragana:"ふくちやまし"},
          {name:"舞鶴市", hiragana:"まいづるし"},
          {name:"綾部市", hiragana:"あやべし"},
          {name:"宇治市", hiragana:"うじし"},
          {name:"宮津市", hiragana:"みやづし"},
          {name:"亀岡市", hiragana:"かめおかし"},
          {name:"城陽市", hiragana:"じょうようし"},
          {name:"向日市", hiragana:"むこうし"},
          {name:"長岡京市", hiragana:"ながおかきょうし"},
          {name:"八幡市", hiragana:"やわたし"},
          {name:"京田辺市", hiragana:"きょうたなべし"},
          {name:"京丹後市", hiragana:"きょうたんごし"},
          {name:"南丹市", hiragana:"なんたんし"},
          {name:"木津川市", hiragana:"きづがわし"},
          {name:"乙訓郡", hiragana:"おとくにぐん"},
          {name:"久世郡", hiragana:"くせぐん"},
          {name:"綴喜郡", hiragana:"つづきぐん"},
          {name:"相楽郡", hiragana:"そうらくぐん"},
          {name:"船井郡", hiragana:"ふないぐん"},
          {name:"与謝郡", hiragana:"よさぐん"},

        ],
      },

      {
        name: "大阪府",
        hiragana: ["おおさかふ"],
        cities: [
          {name:"大阪市", hiragana:"おおさかし"},
          {name:"堺市", hiragana:"さかいし"},
          {name:"岸和田市", hiragana:"きしわだし"},
          {name:"豊中市", hiragana:"とよなかし"},
          {name:"池田市", hiragana:"いけだし"},
          {name:"吹田市", hiragana:"すいたし"},
          {name:"泉大津市", hiragana:"いずみおおつし"},
          {name:"高槻市", hiragana:"たかつきし"},
          {name:"貝塚市", hiragana:"かいづかし"},
          {name:"守口市", hiragana:"もりぐちし"},
          {name:"枚方市", hiragana:"ひらかたし"},
          {name:"茨木市", hiragana:"いばらきし"},
          {name:"八尾市", hiragana:"やおし"},
          {name:"泉佐野市", hiragana:"いずみさのし"},
          {name:"富田林市", hiragana:"とんだばやしし"},
          {name:"寝屋川市", hiragana:"ねやがわし"},
          {name:"河内長野市", hiragana:"かわちながのし"},
          {name:"松原市", hiragana:"まつばらし"},
          {name:"大東市", hiragana:"だいとうし"},
          {name:"和泉市", hiragana:"いずみし"},
          {name:"箕面市", hiragana:"みのおし"},
          {name:"柏原市", hiragana:"かしわらし"},
          {name:"羽曳野市", hiragana:"はびきのし"},
          {name:"門真市", hiragana:"かどまし"},
          {name:"摂津市", hiragana:"せっつし"},
          {name:"高石市", hiragana:"たかいしし"},
          {name:"藤井寺市", hiragana:"ふじいでらし"},
          {name:"東大阪市", hiragana:"ひがしおおさかし"},
          {name:"泉南市", hiragana:"せんなんし"},
          {name:"四條畷市", hiragana:"しじょうなわてし"},
          {name:"交野市", hiragana:"かたのし"},
          {name:"大阪狭山市", hiragana:"おおさかさやまし"},
          {name:"阪南市", hiragana:"はんなんし"},
          {name:"三島郡", hiragana:"みしまぐん"},
          {name:"豊能郡", hiragana:"とよのぐん"},
          {name:"泉北郡", hiragana:"せんぼくぐん"},
          {name:"泉南郡", hiragana:"せんなんぐん"},
          {name:"南河内郡", hiragana:"みなみかわちぐん"},

        ],
      },

      {
        name: "兵庫県",
        hiragana: ["ひょうごけん"],
        cities: [
          {name:"神戸市", hiragana:"こうべし"},
          {name:"姫路市", hiragana:"ひめじし"},
          {name:"尼崎市", hiragana:"あまがさきし"},
          {name:"明石市", hiragana:"あかしし"},
          {name:"西宮市", hiragana:"にしのみやし"},
          {name:"洲本市", hiragana:"すもとし"},
          {name:"芦屋市", hiragana:"あしやし"},
          {name:"伊丹市", hiragana:"いたみし"},
          {name:"相生市", hiragana:"あいおいし"},
          {name:"豊岡市", hiragana:"とよおかし"},
          {name:"加古川市", hiragana:"かこがわし"},
          {name:"赤穂市", hiragana:"あこうし"},
          {name:"西脇市", hiragana:"にしわきし"},
          {name:"宝塚市", hiragana:"たからづかし"},
          {name:"三木市", hiragana:"みきし"},
          {name:"高砂市", hiragana:"たかさごし"},
          {name:"川西市", hiragana:"かわにしし"},
          {name:"小野市", hiragana:"おのし"},
          {name:"三田市", hiragana:"さんだし"},
          {name:"加西市", hiragana:"かさいし"},
          {name:"丹波篠山市", hiragana:"たんばささやまし"},
          {name:"養父市", hiragana:"やぶし"},
          {name:"丹波市", hiragana:"たんばし"},
          {name:"南あわじ市", hiragana:"みなみあわじし"},
          {name:"朝来市", hiragana:"あさごし"},
          {name:"淡路市", hiragana:"あわじし"},
          {name:"宍粟市", hiragana:"しそうし"},
          {name:"加東市", hiragana:"かとうし"},
          {name:"たつの市", hiragana:"たつのし"},
          {name:"川辺郡", hiragana:"かわべぐん"},
          {name:"多可郡", hiragana:"たかぐん"},
          {name:"加古郡", hiragana:"かこぐん"},
          {name:"神崎郡", hiragana:"かんざきぐん"},
          {name:"揖保郡", hiragana:"いぼぐん"},
          {name:"赤穂郡", hiragana:"あこうぐん"},
          {name:"佐用郡", hiragana:"さようぐん"},
          {name:"美方郡", hiragana:"みかたぐん"},

        ],
      },

      {
        name: "奈良県",
        hiragana: ["ならけん"],
        cities: [
          {name:"奈良市", hiragana:"ならし"},
          {name:"大和高田市", hiragana:"やまとたかだし"},
          {name:"大和郡山市", hiragana:"やまとこおりやまし"},
          {name:"天理市", hiragana:"てんりし"},
          {name:"橿原市", hiragana:"かしはらし"},
          {name:"桜井市", hiragana:"さくらいし"},
          {name:"五條市", hiragana:"ごじょうし"},
          {name:"御所市", hiragana:"ごせし"},
          {name:"生駒市", hiragana:"いこまし"},
          {name:"香芝市", hiragana:"かしばし"},
          {name:"葛城市", hiragana:"かつらぎし"},
          {name:"宇陀市", hiragana:"うだし"},
          {name:"山辺郡", hiragana:"やまべぐん"},
          {name:"生駒郡", hiragana:"いこまぐん"},
          {name:"磯城郡", hiragana:"しきぐん"},
          {name:"宇陀郡", hiragana:"うだぐん"},
          {name:"高市郡", hiragana:"たかいちぐん"},
          {name:"北葛城郡", hiragana:"きたかつらぎぐん"},
          {name:"吉野郡", hiragana:"よしのぐん"},

        ],
      },

      {
        name: "和歌山県",
        hiragana: ["わかやまけん"],
        cities: [
          {name:"和歌山市", hiragana:"わかやまし"},
          {name:"海南市", hiragana:"かいなんし"},
          {name:"橋本市", hiragana:"はしもとし"},
          {name:"有田市", hiragana:"ありだし"},
          {name:"御坊市", hiragana:"ごぼうし"},
          {name:"田辺市", hiragana:"たなべし"},
          {name:"新宮市", hiragana:"しんぐうし"},
          {name:"紀の川市", hiragana:"きのかわし"},
          {name:"岩出市", hiragana:"いわでし"},
          {name:"海草郡", hiragana:"かいそうぐん"},
          {name:"伊都郡", hiragana:"いとぐん"},
          {name:"有田郡", hiragana:"ありだぐん"},
          {name:"日高郡", hiragana:"ひだかぐん"},
          {name:"西牟婁郡", hiragana:"にしむろぐん"},
          {name:"東牟婁郡", hiragana:"ひがしむろぐん"},
        ],
      },
    ],
  },

  // 中国地方
  {
    name: "中国",
    hiragana: ["ちゅうごく"],
    prefectures: [
      {
         name: "鳥取県", hiragana: ["とっとりけん"],
         cities: [
          {name:"鳥取市", hiragana:"とりとりし"},
          {name:"米子市", hiragana:"よなごし"},
          {name:"倉吉市", hiragana:"くらよしし"},
          {name:"境港市", hiragana:"さかいみなとし"},
          {name:"岩美郡", hiragana:"いわみぐん"},
          {name:"八頭郡", hiragana:"やずぐん"},
          {name:"東伯郡", hiragana:"とうはくぐん"},
          {name:"西伯郡", hiragana:"さいはくぐん"},
          {name:"日野郡", hiragana:"ひのぐん"},

        ],
       },

      { 
        name: "島根県", hiragana: ["しまねけん"],
        cities: [
          {name:"松江市", hiragana:"まつえし"},
          {name:"浜田市", hiragana:"はまだし"},
          {name:"出雲市", hiragana:"いずもし"},
          {name:"益田市", hiragana:"ますだし"},
          {name:"大田市", hiragana:"おおだし"},
          {name:"安来市", hiragana:"やすぎし"},
          {name:"江津市", hiragana:"ごうつし"},
          {name:"雲南市", hiragana:"うんなんし"},
          {name:"仁多郡", hiragana:"にたぐん"},
          {name:"飯石郡", hiragana:"いいしぐん"},
          {name:"邑智郡", hiragana:"おおちぐん"},
          {name:"鹿足郡", hiragana:"かのあしぐん"},
          {name:"隠岐郡", hiragana:"おきぐん"},

        ],
       },

      { 
        name: "岡山県", hiragana: ["おかやまけん"],
        cities: [
          {name:"岡山市", hiragana:"おかやまし"},
          {name:"倉敷市", hiragana:"くらしきし"},
          {name:"津山市", hiragana:"つやまし"},
          {name:"玉野市", hiragana:"たまのし"},
          {name:"笠岡市", hiragana:"かさおかし"},
          {name:"井原市", hiragana:"いばらし"},
          {name:"総社市", hiragana:"そうじゃし"},
          {name:"高梁市", hiragana:"たかはしし"},
          {name:"新見市", hiragana:"にいみし"},
          {name:"備前市", hiragana:"びぜんし"},
          {name:"瀬戸内市", hiragana:"せとうちし"},
          {name:"赤磐市", hiragana:"あかいわし"},
          {name:"真庭市", hiragana:"まにわし"},
          {name:"美作市", hiragana:"みまさかし"},
          {name:"浅口市", hiragana:"あさくちし"},
          {name:"和気郡", hiragana:"わけぐん"},
          {name:"都窪郡", hiragana:"つくぼぐん"},
          {name:"浅口郡", hiragana:"あさくちぐん"},
          {name:"小田郡", hiragana:"おだぐん"},
          {name:"真庭郡", hiragana:"まにわぐん"},
          {name:"苫田郡", hiragana:"とまたぐん"},
          {name:"勝田郡", hiragana:"かつたぐん"},
          {name:"英田郡", hiragana:"あいだぐん"},
          {name:"久米郡", hiragana:"くめぐん"},
          {name:"加賀郡", hiragana:"かがぐん"},

        ],
       },

      { 
        name: "広島県", hiragana: ["ひろしまけん"],
        cities: [
          {name:"広島市", hiragana:"ひろしまし"},
          {name:"呉市", hiragana:"くれし"},
          {name:"竹原市", hiragana:"たけはらし"},
          {name:"三原市", hiragana:"みはらし"},
          {name:"尾道市", hiragana:"おのみちし"},
          {name:"福山市", hiragana:"ふくやまし"},
          {name:"府中市", hiragana:"ふちゅうし"},
          {name:"三次市", hiragana:"みよしし"},
          {name:"庄原市", hiragana:"しょうばらし"},
          {name:"大竹市", hiragana:"おおたけし"},
          {name:"東広島市", hiragana:"ひがしひろしまし"},
          {name:"廿日市市", hiragana:"はつかいちし"},
          {name:"安芸高田市", hiragana:"あきたかたし"},
          {name:"江田島市", hiragana:"えたじまし"},
          {name:"安芸郡", hiragana:"あきぐん"},
          {name:"山県郡", hiragana:"やまがたぐん"},
          {name:"豊田郡", hiragana:"とよたぐん"},
          {name:"世羅郡", hiragana:"せらぐん"},
          {name:"神石郡", hiragana:"じんせきぐん"},
        ],
       },

      { 
        name: "山口県", hiragana: ["やまぐちけん"],
        cities: [
          {name:"山口市", hiragana:"やまぐちし"},
          {name:"下関市", hiragana:"げっかんし"},
          {name:"宇部市", hiragana:"うべし"},
          {name:"萩市", hiragana:"はぎし"},
          {name:"防府市", hiragana:"ほうふし"},
          {name:"下松市", hiragana:"下松市"},
          {name:"岩国市", hiragana:"いわくにし"},
          {name:"光市", hiragana:"ひかりし"},
          {name:"長門市", hiragana:"ながとし"},
          {name:"柳井市", hiragana:"やないし"},
          {name:"美祢市", hiragana:"みねし"},
          {name:"周南市", hiragana:"しゅうなんし"},
          {name:"山陽小野田市", hiragana:"さんようおのだし"},
          {name:"大島郡", hiragana:"おおしまぐん"},
          {name:"玖珂郡", hiragana:"くがぐん"},
          {name:"熊毛郡", hiragana:"くまげぐん"},
          {name:"阿武郡", hiragana:"あぶぐん"},

        ],
      },
    ],
  },

  // 四国地方
  {
    name: "四国",
    hiragana: ["しこく"],
    prefectures: [
      { 
        name: "徳島県", hiragana: ["とくしまけん"],
        cities: [
          {name:"徳島市", hiragana:"とくしまし"},
          {name:"鳴門市", hiragana:"なるとし"},
          {name:"小松島市", hiragana:"こまつしまし"},
          {name:"阿南市", hiragana:"あなんし"},
          {name:"吉野川市", hiragana:"よしのがわし"},
          {name:"阿波市", hiragana:"あわし"},
          {name:"美馬市", hiragana:"みまし"},
          {name:"三好市", hiragana:"みよしし"},
          {name:"勝浦郡", hiragana:"かつうらぐん"},
          {name:"名東郡", hiragana:"みょうどうぐん"},
          {name:"名西郡", hiragana:"みょうざいぐん"},
          {name:"那賀郡", hiragana:"なかぐん"},
          {name:"海部郡", hiragana:"かいふぐん"},
          {name:"板野郡", hiragana:"いたのぐん"},
          {name:"美馬郡", hiragana:"みまぐん"},
          {name:"三好郡", hiragana:"みよしぐん"},

        ],
       },

      { 
        name: "香川県", hiragana: ["かがわけん"],
        cities: [
          {name:"高松市", hiragana:"たかまつし"},
          {name:"丸亀市", hiragana:"まるがめし"},
          {name:"坂出市", hiragana:"さかいでし"},
          {name:"善通寺市", hiragana:"ぜんつうじし"},
          {name:"観音寺市", hiragana:"かんおんじし"},
          {name:"さぬき市", hiragana:"さぬきし"},
          {name:"東かがわ市", hiragana:"ひがしかがわし"},
          {name:"三豊市", hiragana:"みとよし"},
          {name:"小豆郡", hiragana:"しょうずぐん"},
          {name:"木田郡", hiragana:"きたぐん"},
          {name:"香川郡", hiragana:"かがわぐん"},
          {name:"綾歌郡", hiragana:"あやうたぐん"},
          {name:"仲多度郡", hiragana:"なかたどぐん"},

        ],
       },

      { 
        name: "愛媛県", hiragana: ["えひめけん"],
        cities: [
          {name:"松山市", hiragana:"まつやまし"},
          {name:"今治市", hiragana:"いまばりし"},
          {name:"宇和島市", hiragana:"うわじまし"},
          {name:"八幡浜市", hiragana:"やわたはまし"},
          {name:"新居浜市", hiragana:"にいはまし"},
          {name:"西条市", hiragana:"さいじょうし"},
          {name:"大洲市", hiragana:"おおずし"},
          {name:"伊予市", hiragana:"いよし"},
          {name:"四国中央市", hiragana:"しこくちゅうおうし"},
          {name:"西予市", hiragana:"せいよし"},
          {name:"東温市", hiragana:"とうおんし"},
          {name:"越智郡", hiragana:"おちぐん"},
          {name:"上浮穴郡", hiragana:"かみうけなぐん"},
          {name:"伊予郡", hiragana:"いよぐん"},
          {name:"喜多郡", hiragana:"きたぐん"},
          {name:"西宇和郡", hiragana:"にしうわぐん"},
          {name:"北宇和郡", hiragana:"きたいわぐん"},
          {name:"南宇和郡", hiragana:"みなみうわぐん"},

        ],
       },

      { 
        name: "高知県", hiragana: ["こうちけん"],
        cities: [
          {name:"高知市", hiragana:"こうちし"},
          {name:"室戸市", hiragana:"むろとし"},
          {name:"安芸市", hiragana:"あきし"},
          {name:"南国市", hiragana:"なんかいし"},
          {name:"土佐市", hiragana:"とさし"},
          {name:"須崎市", hiragana:"すさきし"},
          {name:"宿毛市", hiragana:"すくもし"},
          {name:"土佐清水市", hiragana:"とさしみずし"},
          {name:"四万十市", hiragana:"しまんとし"},
          {name:"香南市", hiragana:"こうなんし"},
          {name:"香美市", hiragana:"かみし"},
          {name:"安芸郡", hiragana:"あきぐん"},
          {name:"長岡郡", hiragana:"ながおかぐん"},
          {name:"土佐郡", hiragana:"とさぐん"},
          {name:"吾川郡", hiragana:"あがわぐん"},
          {name:"高岡郡", hiragana:"たかおかぐん"},
          {name:"幡多郡", hiragana:"はたぐん"},

        ],
      },
    ],
  },

  // 九州・沖縄地方
  {
    name: "九州・沖縄",
    hiragana: ["きゅうしゅう・おきなわ"],
    prefectures: [
      { 
        name: "福岡県", hiragana: ["ふくおかけん"],
        cities: [
          {name:"北九州市", hiragana:"きたきゅうしゅうし"},
          {name:"福岡市", hiragana:"ふくおかし"},
          {name:"大牟田市", hiragana:"おおむたし"},
          {name:"久留米市", hiragana:"くるめし"},
          {name:"直方市", hiragana:"のおがたし"},
          {name:"飯塚市", hiragana:"いいづかし"},
          {name:"田川市", hiragana:"たがわし"},
          {name:"柳川市", hiragana:"やながわし"},
          {name:"八女市", hiragana:"やめし"},
          {name:"筑後市", hiragana:"ちくごし"},
          {name:"大川市", hiragana:"おおかわし"},
          {name:"行橋市", hiragana:"ゆくはしし"},
          {name:"豊前市", hiragana:"豊前市"},
          {name:"中間市", hiragana:"なかまし"},
          {name:"小郡市", hiragana:"おごおりし"},
          {name:"筑紫野市", hiragana:"ちくしのし"},
          {name:"春日市", hiragana:"かすがし"},
          {name:"大野城市", hiragana:"おおのじょうし"},
          {name:"宗像市", hiragana:"むなかたし"},
          {name:"太宰府市", hiragana:"だざいふし"},
          {name:"古賀市", hiragana:"こがし"},
          {name:"福津市", hiragana:"ふくつし"},
          {name:"うきは市", hiragana:"うきはし"},
          {name:"宮若市", hiragana:"みやわかし"},
          {name:"嘉麻市", hiragana:"かまし"},
          {name:"朝倉市", hiragana:"あさくらし"},
          {name:"みやま市", hiragana:"みやまし"},
          {name:"糸島市", hiragana:"いとしまし"},
          {name:"那珂川市", hiragana:"なかがわし"},
          {name:"糟屋郡", hiragana:"かすやぐん"},
          {name:"遠賀郡", hiragana:"おんがぐん"},
          {name:"鞍手郡", hiragana:"くらてぐん"},
          {name:"嘉穂郡", hiragana:"かほぐん"},
          {name:"朝倉郡", hiragana:"あさくらぐん"},
          {name:"三井郡", hiragana:"みいぐん"},
          {name:"三瀦郡", hiragana:"みずまぐん"},
          {name:"八女郡", hiragana:"やめぐん"},
          {name:"田川郡", hiragana:"たがわぐん"},
          {name:"京都郡", hiragana:"みやこぐん"},
          {name:"築上郡", hiragana:"ちくじょうぐん"},

        ],
       },

      { 
        name: "佐賀県", hiragana: ["さがけん"],
        cities: [
          {name:"佐賀市", hiragana:"さがし"},
          {name:"唐津市", hiragana:"からつし"},
          {name:"鳥栖市", hiragana:"とすし"},
          {name:"多久市", hiragana:"たくし"},
          {name:"伊万里市", hiragana:"いまりし"},
          {name:"武雄市", hiragana:"たけおし"},
          {name:"鹿島市", hiragana:"かしまし"},
          {name:"小城市", hiragana:"おぎし"},
          {name:"嬉野市", hiragana:"うれしのし"},
          {name:"神埼市", hiragana:"かんざきし"},
          {name:"神埼郡", hiragana:"かんざきぐん"},
          {name:"三養基郡", hiragana:"みやきぐん"},
          {name:"東松浦郡", hiragana:"ひがしまつうらぐん"},
          {name:"西松浦郡", hiragana:"にしまつうらぐん"},
          {name:"杵島郡", hiragana:"きしまぐん"},
          {name:"藤津郡", hiragana:"ふじつぐん"},
          
        ],
       },
      
       { 
        name: "長崎県", hiragana: ["ながさきけん"],
        cities: [
          {name:"長崎市", hiragana:"ながさきし"},
          {name:"佐世保市", hiragana:"させぼし"},
          {name:"島原市", hiragana:"しまばらし"},
          {name:"諫早市", hiragana:"いさはやし"},
          {name:"大村市", hiragana:"おおむらし"},
          {name:"平戸市", hiragana:"ひらどし"},
          {name:"松浦市", hiragana:"まつうらし"},
          {name:"対馬市", hiragana:"つしまし"},
          {name:"壱岐市", hiragana:"いきし"},
          {name:"五島市", hiragana:"ごとうし"},
          {name:"西海市", hiragana:"さいかいし"},
          {name:"雲仙市", hiragana:"うんぜんし"},
          {name:"南島原市", hiragana:"みなみしまばらし"},
          {name:"西彼杵郡", hiragana:"にしそのぎぐん"},
          {name:"東彼杵郡", hiragana:"ひがしそのぎぐん"},
          {name:"北松浦郡", hiragana:"きたまつうらぐん"},
          {name:"南松浦郡", hiragana:"みなみまつうらぐん"},

        ],
       },

      { 
        name: "熊本県", hiragana: ["くまもとけん"],
        cities: [
          {name:"熊本市", hiragana:"くまもとし"},
          {name:"八代市", hiragana:"やつしろし"},
          {name:"人吉市", hiragana:"ひとよしし"},
          {name:"荒尾市", hiragana:"あらおし"},
          {name:"水俣市", hiragana:"みなまたし"},
          {name:"玉名市", hiragana:"たまなし"},
          {name:"山鹿市", hiragana:"やまがし"},
          {name:"菊池市", hiragana:"きくちし"},
          {name:"宇土市", hiragana:"うとし"},
          {name:"上天草市", hiragana:"かみあまくさし"},
          {name:"宇城市", hiragana:"うきし"},
          {name:"阿蘇市", hiragana:"あそし"},
          {name:"天草市", hiragana:"あまくさし"},
          {name:"合志市", hiragana:"こうしし"},
          {name:"下益城郡", hiragana:"しもましきぐん"},
          {name:"玉名郡", hiragana:"たまなぐん"},
          {name:"菊池郡", hiragana:"きくちぐん"},
          {name:"阿蘇郡", hiragana:"あそぐん"},
          {name:"上益城郡", hiragana:"かみましきぐん"},
          {name:"八代郡", hiragana:"やつしろぐん"},
          {name:"葦北郡", hiragana:"あしきたぐん"},
          {name:"球磨郡", hiragana:"くまぐん"},
          {name:"天草郡", hiragana:"あまくさぐん"},
          
        ],
       },

      { 
        name: "大分県", hiragana: ["おおいたけん"],
        cities: [
          {name:"大分市", hiragana:"おおいたし"},
          {name:"別府市", hiragana:"べっぷし"},
          {name:"中津市", hiragana:"なかつし"},
          {name:"日田市", hiragana:"ひたし"},
          {name:"佐伯市", hiragana:"さいきし"},
          {name:"臼杵市", hiragana:"うすきし"},
          {name:"津久見市", hiragana:"つくみし"},
          {name:"竹田市", hiragana:"たけたし"},
          {name:"豊後高田市", hiragana:"ぶんごたかだし"},
          {name:"杵築市", hiragana:"きつきし"},
          {name:"宇佐市", hiragana:"うさし"},
          {name:"豊後大野市", hiragana:"ぶんごおおのし"},
          {name:"由布市", hiragana:"ゆふし"},
          {name:"国東市", hiragana:"くにさきし"},
          {name:"東国東郡", hiragana:"ひがしくにさきぐん"},
          {name:"速見郡", hiragana:"はやみぐん"},
          {name:"玖珠郡", hiragana:"くすぐん"},

        ],
       },

      { 
        name: "宮崎県", hiragana: ["みやざきけん"],
        cities: [
          {name:"宮崎市", hiragana:"みやざきし"},
          {name:"都城市", hiragana:"みやこのじょうしし"},
          {name:"延岡市", hiragana:"のべおかし"},
          {name:"日南市", hiragana:"にちなんし"},
          {name:"小林市", hiragana:"こばやしし"},
          {name:"日向市", hiragana:"ひゅうがし"},
          {name:"串間市", hiragana:"くしまし"},
          {name:"西都市", hiragana:"さいとし"},
          {name:"えびの市", hiragana:"えびのし"},
          {name:"北諸県郡", hiragana:"きたもろかたぐん"},
          {name:"西諸県郡", hiragana:"にしもろかたぐん"},
          {name:"東諸県郡", hiragana:"ひがしもろかたぐん"},
          {name:"児湯郡", hiragana:"こゆぐん"},
          {name:"東臼杵郡", hiragana:"ひがしうすきぐん"},
          {name:"西臼杵郡", hiragana:"にしうすきぐん"},

        ],
       },

      { 
        name: "鹿児島県", hiragana: ["かごしまけん"],
        cities: [
          {name:"鹿児島市", hiragana:"かごしまし"},
          {name:"鹿屋市", hiragana:"かのやし"},
          {name:"枕崎市", hiragana:"まくらざきし"},
          {name:"阿久根市", hiragana:"あくねし"},
          {name:"出水市", hiragana:"いずみし"},
          {name:"指宿市", hiragana:"いぶすきし"},
          {name:"西之表市", hiragana:"にしのおもてし"},
          {name:"垂水市", hiragana:"たるみずし"},
          {name:"薩摩川内市", hiragana:"さつませんだいし"},
          {name:"日置市", hiragana:"ひおきし"},
          {name:"曽於市", hiragana:"そおし"},
          {name:"霧島市", hiragana:"きりしまし"},
          {name:"いちき串木野市", hiragana:"いちきくしきのし"},
          {name:"南さつま市", hiragana:"みなみさつまし"},
          {name:"志布志市", hiragana:"しぶしし"},
          {name:"奄美市", hiragana:"あまみし"},
          {name:"南九州市", hiragana:"みなみきゅうしゅうし"},
          {name:"伊佐市", hiragana:"いさし"},
          {name:"姶良市", hiragana:"あいらし"},
          {name:"鹿児島郡", hiragana:"かごしまぐん"},
          {name:"薩摩郡", hiragana:"さつまぐん"},
          {name:"出水郡", hiragana:"いずみぐん"},
          {name:"姶良郡", hiragana:"あいらぐん"},
          {name:"曽於郡", hiragana:"そおぐん"},
          {name:"肝属郡", hiragana:"きもつきぐん"},
          {name:"熊毛郡", hiragana:"くまげぐん"},
          {name:"大島郡", hiragana:"おおしまぐん"},
          
        ],
       },

      { 
        name: "沖縄県", hiragana: ["おきなわけん"],
        cities: [
          {name:"那覇市", hiragana:"なはし"},
          {name:"宜野湾市", hiragana:"ぎのわんし"},
          {name:"石垣市", hiragana:"いしがきし"},
          {name:"浦添市", hiragana:"うらそえし"},
          {name:"名護市", hiragana:"なごし"},
          {name:"糸満市", hiragana:"いとまんし"},
          {name:"沖縄市", hiragana:"おきなわし"},
          {name:"豊見城市", hiragana:"とみぐすくし"},
          {name:"うるま市", hiragana:"うるまし"},
          {name:"宮古島市", hiragana:"みやこじまし"},
          {name:"南城市", hiragana:"なんじょうし"},
          {name:"国頭郡", hiragana:"くにがみぐん"},
          {name:"中頭郡", hiragana:"なかがみぐん"},
          {name:"島尻郡", hiragana:"しまじりぐん"},
          {name:"宮古郡", hiragana:"みやこぐん"},
          {name:"八重山郡", hiragana:"やえやまぐん"},

        ],
      },
    ],
  },
];
